-- Special resources: Star Legend, Star Outfit, and Yuanliu Outfit.

create table public.star_legend_resources (
  id bigint generated by default as identity primary key,
  skin_profile_id bigint not null references public.skin_profiles(id) on delete restrict,
  name text not null,
  date date not null,
  release_type text not null default '首发' check (release_type in ('首发', '返场')),
  quality text not null default '传说',
  tag text not null default '',
  obtain text not null default '',
  price text not null default '',
  permanent text not null default '否' check (permanent in ('是', '否')),
  img_url text,
  tag_img_url text,
  notes text,
  is_available boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint star_legend_resource_event_unique
    unique (skin_profile_id, name, date, release_type)
);

create table public.star_outfit_resources (
  id bigint generated by default as identity primary key,
  skin_profile_id bigint not null references public.skin_profiles(id) on delete restrict,
  name text not null,
  date date not null,
  release_type text not null default '首发' check (release_type in ('首发', '返场')),
  obtain text not null default '',
  price text not null default '',
  img_url text,
  notes text,
  is_available boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint star_outfit_resource_event_unique
    unique (skin_profile_id, name, date, release_type)
);

create table public.yuanliu_suit_resources (
  id bigint generated by default as identity primary key,
  name text not null,
  date date not null,
  release_type text not null default '首发' check (release_type in ('首发', '返场')),
  quality text,
  tag text,
  collab text,
  obtain text not null default '',
  price text not null default '',
  permanent text not null default '否' check (permanent in ('是', '否')),
  img_url text,
  tag_img_url text,
  notes text,
  is_available boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint yuanliu_suit_resource_event_unique
    unique (name, date, release_type)
);

create index idx_star_legend_skin_profile
  on public.star_legend_resources (skin_profile_id);
create index idx_star_legend_date
  on public.star_legend_resources (date desc);
create index idx_star_outfit_skin_profile
  on public.star_outfit_resources (skin_profile_id);
create index idx_star_outfit_date
  on public.star_outfit_resources (date desc);
create index idx_yuanliu_suit_date
  on public.yuanliu_suit_resources (date desc);

create trigger star_legend_resources_updated_at
  before update on public.star_legend_resources
  for each row execute function public.update_updated_at();
create trigger star_outfit_resources_updated_at
  before update on public.star_outfit_resources
  for each row execute function public.update_updated_at();
create trigger yuanliu_suit_resources_updated_at
  before update on public.yuanliu_suit_resources
  for each row execute function public.update_updated_at();

alter table public.star_legend_resources enable row level security;
alter table public.star_outfit_resources enable row level security;
alter table public.yuanliu_suit_resources enable row level security;

create policy "Public read available star legend resources"
  on public.star_legend_resources for select
  to anon, authenticated
  using (is_available);
create policy "Public read available star outfit resources"
  on public.star_outfit_resources for select
  to anon, authenticated
  using (is_available);
create policy "Public read available yuanliu suit resources"
  on public.yuanliu_suit_resources for select
  to anon, authenticated
  using (is_available);

revoke all on table public.star_legend_resources from anon, authenticated;
revoke all on table public.star_outfit_resources from anon, authenticated;
revoke all on table public.yuanliu_suit_resources from anon, authenticated;
grant select on table public.star_legend_resources to anon, authenticated;
grant select on table public.star_outfit_resources to anon, authenticated;
grant select on table public.yuanliu_suit_resources to anon, authenticated;
grant all on table public.star_legend_resources to service_role;
grant all on table public.star_outfit_resources to service_role;
grant all on table public.yuanliu_suit_resources to service_role;
grant usage, select on sequence public.star_legend_resources_id_seq to service_role;
grant usage, select on sequence public.star_outfit_resources_id_seq to service_role;
grant usage, select on sequence public.yuanliu_suit_resources_id_seq to service_role;
